"""Run after changing frontend files: python3 tools/build-pwa.py.
Regenerates the offline app shell and its version. No server access required.
"""
from pathlib import Path
import hashlib, json, re
root=Path(__file__).resolve().parent.parent
html=(root/'index.html').read_text()
paths={'index.html','manifest.webmanifest','emoji-data.json','texttura-icon.png'}
for value in re.findall(r'(?:src|href)="([^"#]+)"',html):
 path=value.split('?')[0]
 if not path.startswith(('http:','https:','data:')) and (root/path).is_file(): paths.add(path)
paths.update(str(p.relative_to(root)) for p in (root/'icons').glob('*.png'))
assets={path:hashlib.sha256((root/path).read_bytes()).hexdigest() for path in sorted(paths)}
revision=hashlib.sha256(json.dumps(assets,sort_keys=True).encode()).hexdigest()[:16]
worker="""// Generated by tools/build-pwa.py. Rebuild after changing app files.
'use strict';
const REVISION = __REVISION__;
const ASSETS = __ASSETS__;
const ROOT = new URL('./', self.location.href);
const PREFIX = 'texttura-shell:' + ROOT.pathname + ':';
const CACHE = PREFIX + REVISION;
self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    try {
      await Promise.all(Object.entries(ASSETS).map(async ([path, hash]) => {
        const url = new URL(path, ROOT).href;
        const response = await fetch(url, {cache:'reload', credentials:'same-origin'});
        if (!response.ok) throw new Error('App asset unavailable: ' + path);
        const bytes = await response.clone().arrayBuffer();
        const digest = Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256', bytes)))
          .map(n => n.toString(16).padStart(2, '0')).join('');
        if (digest !== hash) throw new Error('Incomplete app release: ' + path);
        await cache.put(url, response);
      }));
    } catch (error) {
      await caches.delete(CACHE);
      throw error;
    }
    // Do not call skipWaiting here: an open post must not be interrupted.
  })());
});
self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) {
      if (key.startsWith(PREFIX) && key !== CACHE) await caches.delete(key);
    }
    // No clients.claim(): initial installation does not switch a live page.
  })());
});
self.addEventListener('message', event => {
  if (event.data && event.data.type === 'TEXTTURA_APPLY_UPDATE') event.waitUntil(self.skipWaiting());
});
self.addEventListener('fetch', event => {
  const request = event.request;
  const url = new URL(request.url);
  // Cloud/API responses, external resources, and writes are never cached here.
  if (request.method !== 'GET' || url.origin !== ROOT.origin || !url.pathname.startsWith(ROOT.pathname)) return;
  let path = url.pathname.slice(ROOT.pathname.length);
  if (request.mode === 'navigate' && (path === '' || path === 'index.html')) path = 'index.html';
  if (!Object.prototype.hasOwnProperty.call(ASSETS, path)) return;
  event.respondWith((async () => {
    const response = await (await caches.open(CACHE)).match(new URL(path, ROOT).href);
    return response || fetch(request);
  })());
});
"""
worker=worker.replace('__REVISION__',json.dumps(revision)).replace('__ASSETS__',json.dumps(assets,ensure_ascii=False,indent=2))
(root/'sw.js').write_text(worker)
print(f'PWA revision {revision}, {len(assets)} local files')
