// Generated by build-pwa.py. Rebuild after changing app files.
'use strict';
const REVISION = "c1f5e8dd3dc03ac4";
const ASSETS = {
  "app-install.css": "6cea7e09df9787d7040d3205c12e952e830717af3bdaafa7caacc643af1f2b47",
  "app-install.js": "3129641b7a8fa8bddd1065be441ebe8ae74d9c0f3801c77dfe1716073d6fe5fe",
  "apple-touch-icon.png": "6435d66d4ebf1bcbbbb2da15b73aa8468e832fbc83b874f48e422782606435ad",
  "cloud-save.js": "e1af38b7bd6d9fb97966d0e07e40fe420fbb53909dc663a353dfb10e51d1543d",
  "collapse-on-load.js": "84d712cb051092ab7e7be95224aed75cfcd3ff294e929abeaecf4f9dd425cc1b",
  "core.js": "0138a13df375a0a243137089f4670474a7b9b36aa86e35c67d1e5cea2c59124c",
  "editor-events.js": "2381363a3439720bc3eedb6060b5f93aa75f03d0310b1ed01f4d74eee4055976",
  "emoji-data.json": "8aeb5a343ad65ac1e52231bc93c5277557cee34b2dd6f45db51e03844aa56722",
  "emoji-pro.css": "bbfef91b95c2a2a381ac35df3cc5ff0a2057b1b34d47d6404a71fa0ecc0f49b1",
  "emoji-pro.js": "30a50c645b3c3951352db433566332e718e0dc69054c2322f6a4ef77329da367",
  "export.js": "da25c1338e276d11173a5d176618fc00190aa585850c5fed844356d9c3f3914e",
  "font-sheet-panel.js": "39e02a858f26fb05dc8931a04b0e91b248f9eaa84d65bc6531428ee717b0c343",
  "font-sheet.css": "310e736e427daeb0ec324ece384fcef5b639aa569d39d54f5bd5facdaedb5e91",
  "font-sheet.js": "fdde1806c7282855e1901c9ca7b8333b38fe654efd3946eee4946794204503fb",
  "format-range.js": "2eb357c6e1dd7452db2e0ce70c73a07f1261a25950c67681897115e31551bf9e",
  "history.js": "dee1b044bad6547c387441b57c2fbb4c69357bd204b26c38ff348cc5fa6c660d",
  "icon-192.png": "eacfd8683dd5d7f2a94d42c8fb61594b6c948c4ec4fe3f8ab9ed4ab51ad32830",
  "icon-512.png": "4e07b0682baf7bb472716762b85a67d190fe0f4f7f9fb07ed38ef5cfcea2d043",
  "icon-maskable-512.png": "1ce13244f5445d7d119cfd328cd4d3d46a23b9ea261401e31cb5e6f4c415edd9",
  "image-ui.js": "1c1330d08f89bec7640228b9e978944cc334a2cf2a531d6fd415a4642ffe78a5",
  "images.js": "702e8a1da76c5edbe0adddc45863c96c0fd0eea6820966854c829e7d504970b7",
  "index.html": "125ff969f3955d336b1092b5f48a7dc7c567f4bc8ded50d78df863703605646c",
  "local-draft.js": "b72c06082d3a500488ad033e249b21dfeec2bac302647c3ec8f5c20c73035d84",
  "manifest.webmanifest": "f4cb0ca5933b931d037c3bff9aa53df166aa265f0a6a9f18d817ecdea8c9f8e6",
  "panel-blocks.css": "3ef3f77111d394b7e80334c815d951592cc3e089b520f9be3a38c1067d5c005f",
  "panel-blocks.js": "bde19f73988384f2b539cf1e636b9428b2dfc9aec802ae3a95547825a78d17d4",
  "panel-fixes.js": "4892f2a5c0887b8529cba483af667c2b3d2404fb614e3339e07b860d4d058538",
  "post-tools.js": "3a9689671a557aad544d24422c6fb77f0a4188cd704d5a86aee95471c45eb208",
  "range-engine.js": "75d7be09c7e6979105761b930c684745d70d8d16767f579128236e699a3a71f5",
  "ratio-fix.js": "b1a873a5f906db0210df4f67af10e7d5ef94c77abc4ff3d2cf2a3c153407ae05",
  "selection-sync.js": "ccf62b80bb2c1d9694ea9dd6d2b5ea044db69283df0d2897b163493f933a5e7d",
  "settings.js": "0dd616226f981671e4b8be071d73109aa9518f1db8f97ad7c693cd83801bfaa4",
  "size-align.css": "353a01412acdc132a827e0683a9a1f0182ff0a2abca96f2b54c2a1ce00e6e39e",
  "size-align.js": "250175944fe53b7ed89cbe7d7f507e357d1bde7d2f906d70771044c9a84d3ba6",
  "styles.css": "7a8135f1ad43d6093e21d1c93d0f8129d6bf1555d12b383e4ca5bb25c3807e43",
  "textbox.js": "cc84dc8fdba8f5a77de98bee8e4a6992df9b6a93c84ecb5e1c28f62f42917de0",
  "texttura-gloss.css": "c7000f45fafe29019e9795a4fed36962a438ff9aa678b6110f8a5f2efaf4d328",
  "texttura-icon.png": "51ba742c539a78f0332c0920feff2a1d3b166798d87c7a7546f021e473ffbc04",
  "ui.js": "db9a08fdbc9265329b0f5d359b24297a2446157b4a0097490cb9e10a06d9cb66",
  "zoom.js": "92208d350759dd669e37b0a2e4637c8f6af4621c78479d99c3ff450967fc20fc"
};
const ROOT = new URL('./', self.location.href);
const PREFIX = 'texttura-shell:' + ROOT.pathname + ':';
const CACHE = PREFIX + REVISION;
self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    try {
      await Promise.all(Object.entries(ASSETS).map(async ([path, hash]) => {
        const url = new URL(path, ROOT).href;
        const response = await fetch(url, {cache:'reload', credentials:'same-origin'});
        if (!response.ok) throw new Error('App asset unavailable: ' + path);
        const bytes = await response.clone().arrayBuffer();
        const digest = Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256', bytes)))
          .map(n => n.toString(16).padStart(2, '0')).join('');
        if (digest !== hash) throw new Error('Incomplete app release: ' + path);
        await cache.put(url, response);
      }));
    } catch (error) {
      await caches.delete(CACHE);
      throw error;
    }
    // Do not call skipWaiting here: an open post must not be interrupted.
  })());
});
self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) {
      if (key.startsWith(PREFIX) && key !== CACHE) await caches.delete(key);
    }
    // No clients.claim(): initial installation does not switch a live page.
  })());
});
self.addEventListener('message', event => {
  if (event.data && event.data.type === 'TEXTTURA_APPLY_UPDATE') event.waitUntil(self.skipWaiting());
});
self.addEventListener('fetch', event => {
  const request = event.request;
  const url = new URL(request.url);
  // Cloud/API responses, external resources, and writes are never cached here.
  if (request.method !== 'GET' || url.origin !== ROOT.origin || !url.pathname.startsWith(ROOT.pathname)) return;
  let path = url.pathname.slice(ROOT.pathname.length);
  if (request.mode === 'navigate' && (path === '' || path === 'index.html')) path = 'index.html';
  if (!Object.prototype.hasOwnProperty.call(ASSETS, path)) return;
  event.respondWith((async () => {
    const response = await (await caches.open(CACHE)).match(new URL(path, ROOT).href);
    return response || fetch(request);
  })());
});
